//活动组件脚本
var campaign_modules = [
    {
        'name':'RichComment',
        'note':'评论',
        'enable':true
    },
    {
        'name':'ScoreBoard',
        'note':'比分扳',
        'enable':true
    },
    {
        'name':'TodoList',
        'note':'目标列表',
        'enable':true,
    },
    {
        'name':'Formation',
        'note':'阵型图',
        'enable':true
    },
    {
        'name':'LiteralResult',
        'note':'结果描述',
        'enable':true
    },
    {
        'name':'RunningStatistic',
        'note':'跑步统计',
        'enable':true
    }
];
try{
    campaign_modules.forEach(function (module) {
        db.campaignmodules.insert(module);
    });
} catch (e){
    print(e);
};
//活动类型脚本
var molds = [
    {
        'name':'羽毛球',
        'module':['RichComment','ScoreBoard'],
        'enable':true
    },
    {
        'name':'篮球',
        'module':['RichComment','ScoreBoard'],
        'enable':true
    },
    {
        'name':'阅读',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'自行车',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'下午茶',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'棋牌',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'足球',
        'module':['RichComment','ScoreBoard'],
        'enable':true
    },
    {
        'name':'k歌',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'健身',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'美食',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'跑步',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'亲子',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'影视',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'摄影',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'旅行',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'桌游',
        'module':['RichComment'],
        'enable':true
    },
    {
        'name':'其它',
        'module':['RichComment'],
        'enable':true
    },
];
try{
    molds.forEach(function (mold) {
        db.campaignmolds.insert(mold);
    });
} catch (e){
    print(e);
};